# Generated by Django 5.2.14 on 2026-05-16 09:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='negocio',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='recomendacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='alerta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='leida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.negocio'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('stock_critico', 'Stock Crítico'), ('sin_movimiento', 'Sin Movimiento'), ('baja_ventas', 'Baja de Ventas'), ('sobreinventario', 'Sobreinventario')], max_length=50),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='inventario.negocio'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.compra'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.venta'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='tipo_negocio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.negocio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='inventario.negocio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='aplicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='inventario.negocio'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='tipo',
            field=models.CharField(choices=[('reabastecer', 'Reabastecer'), ('promocion', 'Promoción'), ('descuento', 'Descuento'), ('descontinuar', 'Descontinuar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='inventario.negocio'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='tipo_plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('premium', 'Premium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='inventario.negocio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado')], default='empleado', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='inventario.negocio'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
